### ISSUE TITLE
Error downloading references

### ISSUE THREAD

**Issue by Dagsbio** [nf-core/rnafusion#174]
Hi, I finally managed to get access to a cluster so I can finally run rnafusion.

But I am getting this error now:

![image](https://user-images.githubusercontent.com/23311037/105559184-cfaccb80-5d10-11eb-90bf-e8605af4b391.png)

Any ideas?

**Comment by Dagsbio** [comment]
command used was:
 
 nextflow run nf-core/rnafusion/download-references.nf -profile singularity --download_all --outdir  nf-core_rnafusion/ --cosmic_usr xxxxx --cosmic_passwd xxxxx

**Comment by MaxUlysse** [comment]
Hi @Dagsbio this is more an issue with the downloading of the singularity image actually.
Can you try if the command `singularity pull --name nfcore-rnafusion-1.2.0.img docker://nfcore/rnafusion:1.2.0` actually works or your cluster?
Additional question, what is the singularity version on said cluster?

**Comment by Dagsbio** [comment]
Hi,

Looks like that command works:

[image: image.png]

And the version is:

3.4.1-4.2.ohpc.1.3.9

**Comment by Dagsbio** [comment]
Here is the image again, not sure you can view it in the previous post:
![image](https://user-images.githubusercontent.com/23311037/105693662-4956dc00-5f00-11eb-95d4-7c9ba31c967e.png)

**Comment by MaxUlysse** [comment]
I'm assuming that you haven't set up a singularity cache directory (cf: https://www.nextflow.io/docs/latest/config.html#scope-singularity) given the first image.
I'd recommend to do that, so that you'll be able to share the images between several runs.
You can do that in a config file. cf: https://github.com/nf-core/configs/blob/master/conf/cbe.config
What actually failed was not the rnafusion process to download star_fusion, but the part where Nextflow is downloading the singularity image.
If you set the singularity cache dir properly and put this singularity image there, the process will work.
If you feel like you don't need to set up a singularity cache dir, you can put the image you just downloaded to the default one for Nextflow (in the work directory, so in your case: `/home/nfs1/dgomez/work/singularity/`).

**Comment by Dagsbio** [comment]
Hi, actually I didn't let that c ommand to finish... 

This is what I get.

How can make this work this first?

![image](https://user-images.githubusercontent.com/23311037/105698372-1283c480-5f06-11eb-8f27-f55cb6c372f7.png)

Thank you!

**Comment by MaxUlysse** [comment]
It could be due to some SSL certificate problems...
Could you try downloading the image locally and then transferring it to the cluster?
