### ISSUE TITLE
Various warnings and errors when running 

### ISSUE THREAD

**Issue by Dagsbio** [nf-core/rnafusion#175]
Hi again, I finally downloaded everything neccesary in a different machine and then sent it to the cluster. Then I tried to run the program.

-Command used (40 cpus and 100000 Mb RAM):

**srun -n40 --mem=100000 nextflow run nf-core/rnafusion -profile singularity --reads 'TP44_R{1,2}.fastq.gz' --genomes_base nf-core_rnafusion/ --arriba --star_fusion --fusioncatcher --ericscript --pizzly --squid   --arriba_vis --fusion_inspector**

-Errors:

1) Can't lock file: /home/nfs1/dgomez/.nextflow/history -- Nextflow needs to run in a file system that supports file locks
srun: error: quimera101: tasks 0-1,4-10,17-20,22,24,28,33-34,36: Exited with exit code 1
![image](https://user-images.githubusercontent.com/23311037/105980719-82748500-6095-11eb-9e62-c6a30b65211f.png)

2)Error executing process > 'pizzly (TP44_R)' / ericscript / fusioncatcher...

![image](https://user-images.githubusercontent.com/23311037/105980828-a1731700-6095-11eb-9115-34b162b70992.png)

Any ideas what's going wrong?

Thank you

**Comment by MaxUlysse** [comment]
First issue looks like a Nextflow issue, not sure how to fix that, but I'd advise looking on the Nextflow GitHub, or talking to your admins to have this fixed.
Second seems like Nexflow tried to pull the `nfcore-rnafusion-ericscript_0.5.5.img` container which seems to be causing issue on your system, mainly due to `mksquashf` not being available.
I'd recommend either downloading it from somewhere else, and then transfering it here, or talk with your admins to have the singularity install fixed
