### ISSUE TITLE
Add EricScript

### ISSUE THREAD

**Issue by ewels** [nf-core/rnafusion#4]
_From @ewels on March 13, 2018 10:48_

_Copied from original issue: SciLifeLab/NGI-RNAfusion#8_

**Comment by matq007** [comment]
We have to install the tool manually for now, because the conda installation has conflict with `samtools`. I'm testing the tool right now and it looks like it works fine with the latest `samtools`. I have found a conda recipie [here](https://bioconda.github.io/recipes/ericscript/README.html). I have to figure out how to make a PR.

**Comment by matq007** [comment]
The only solution is to create environment specifically for this tool and use it in the pipeline. 
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - ericscript=0.5.5 -> samtools==0.1.19
  - fusion-inspector=1.2.0 -> samtools[version='>=1.3']
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ewels** [comment]
Ah if there's no obvious reason for the bioconda samtools version fix then yeah, it would be great to simply update the bioconda recipe! It seems suspicious that just that version is locked, but if you tested it and it works then I think it's fine to go ahead with a PR on bioconda 👍

**Comment by matq007** [comment]
There is some issue when it comes to the singularity. The tool is creating some file during execution in /opt/env/... meaning that the read-only singularity image will fail. I've tried using `--sandbox` parameter to build the image. The process runs but doesn't find any fusions which is odd, because running the tool in Docker actually produces fusions.
